import { Diagnosis, Medication, LabTest, Imaging, Referral } from "../src/lib/clinicalEngine";
export const DIAGNOSIS_DB: Diagnosis[] = [
  // ── RESPIRATORY ──────────────────────────────────────────────────────────────
  {
    id: "uri", name: "Upper Respiratory Tract Infection", icd10: "J06.9",
    system: "Respiratory", severity: "mild", prevalence: "common",
    symptoms: ["cold", "runny nose", "sore throat", "sneezing", "nasal congestion", "mild fever", "cough"],
    redFlags: ["high fever", "difficulty breathing", "stridor"],
    medications: [
      { drug: "Paracetamol 500mg", dose: "500–1000mg", route: "Oral", frequency: "TDS", duration: "3–5 days", notes: "1st line — fever/pain" },
      { drug: "Ibuprofen 400mg", dose: "400mg", route: "Oral", frequency: "TDS with food", duration: "3 days", notes: "NSAID — avoid in peptic ulcer" },
      { drug: "Cetirizine 10mg", dose: "10mg", route: "Oral", frequency: "OD (night)", duration: "5 days", notes: "Antihistamine — sneezing, rhinorrhoea" },
      { drug: "Levocetirizine 5mg", dose: "5mg", route: "Oral", frequency: "OD night", duration: "5 days", notes: "Alternative antihistamine" },
      { drug: "Saline Nasal Spray (0.9% NaCl)", dose: "2 sprays/nostril", route: "Topical", frequency: "TDS", duration: "7 days", notes: "Nasal hygiene — no side effects" },
      { drug: "Xylometazoline 0.1% Nasal Drops", dose: "2–3 drops/nostril", route: "Topical", frequency: "BD–TDS", duration: "Max 3 days", notes: "⚠️ Rebound congestion if >3 days" },
      { drug: "Amoxicillin 500mg", dose: "500mg", route: "Oral", frequency: "TDS", duration: "5–7 days", notes: "Only if secondary bacterial infection suspected" },
      { drug: "Benzydamine HCl Throat Spray", dose: "4–8 sprays", route: "Topical", frequency: "Q3h", duration: "5 days", notes: "For sore throat" },
      { drug: "Dextromethorphan 15mg", dose: "15mg", route: "Oral", frequency: "TDS", duration: "3–5 days", notes: "Dry cough suppressant" },
      { drug: "Guaifenesin 200mg", dose: "200mg", route: "Oral", frequency: "TDS", duration: "5 days", notes: "Expectorant — productive cough" },
    ],
    labTests: [
      { name: "Complete Blood Count (CBC)", code: "CBC", urgency: "routine", reason: "Differentiate viral vs bacterial" },
      { name: "CRP", code: "CRP", urgency: "routine", reason: "Assess inflammation" },
    ],
    imaging: [],
    referrals: [{ specialty: "ENT", urgency: "routine", reason: "If recurrent or complicated" }],
    notes: "Mostly viral — antibiotics NOT indicated unless secondary bacterial infection suspected.",
  },
  {
    id: "pneumonia", name: "Community-acquired Pneumonia", icd10: "J18.9",
    system: "Respiratory", severity: "severe", prevalence: "common",
    symptoms: ["fever", "cough", "chest pain", "breathlessness", "sputum", "fatigue", "chills"],
    redFlags: ["SpO2 < 94%", "respiratory rate > 25", "confusion", "hypotension"],
    medications: [
      { drug: "Amoxicillin-Clavulanate 625mg", dose: "625mg", route: "Oral", frequency: "TDS", duration: "7 days", notes: "1st line empirical — mild-moderate CAP" },
      { drug: "Azithromycin 500mg", dose: "500mg", route: "Oral", frequency: "OD", duration: "5 days", notes: "Atypical organism coverage (Mycoplasma, Chlamydia)" },
      { drug: "Doxycycline 100mg", dose: "100mg", route: "Oral", frequency: "BD", duration: "7 days", notes: "Alternative for atypicals — avoid in pregnancy" },
      { drug: "Levofloxacin 750mg", dose: "750mg", route: "Oral", frequency: "OD", duration: "5 days", notes: "Respiratory FQ — allergy cases or treatment failure" },
      { drug: "IV Ceftriaxone 1g", dose: "1g", route: "IV", frequency: "OD", duration: "5–7 days", notes: "Severe CAP requiring hospitalisation" },
      { drug: "IV Piperacillin-Tazobactam 4.5g", dose: "4.5g", route: "IV", frequency: "Q8h", duration: "7–10 days", notes: "Hospital-acquired / aspiration pneumonia" },
      { drug: "Paracetamol 650mg", dose: "650mg", route: "Oral", frequency: "TDS PRN", duration: "As needed", notes: "Antipyretic / analgesia" },
      { drug: "IV Hydrocortisone 100mg", dose: "100mg", route: "IV", frequency: "Q8h", duration: "3 days", notes: "Severe CAP with sepsis — adjunct steroid" },
      { drug: "Oseltamivir 75mg", dose: "75mg", route: "Oral", frequency: "BD", duration: "5 days", notes: "If influenza-associated pneumonia suspected" },
    ],
    labTests: [
      { name: "CBC with Differential", code: "CBC-DIFF", urgency: "urgent", reason: "WBC for infection severity" },
      { name: "CRP / ESR", code: "CRP-ESR", urgency: "urgent", reason: "Inflammatory markers" },
      { name: "Sputum Culture & Sensitivity", code: "SPUTUM-CS", urgency: "urgent", reason: "Pathogen identification" },
      { name: "Blood Culture (x2)", code: "BLOOD-CX", urgency: "stat", reason: "Bacteremia if severe" },
      { name: "Procalcitonin", code: "PCT", urgency: "urgent", reason: "Bacterial vs viral" },
      { name: "ABG (Arterial Blood Gas)", code: "ABG", urgency: "stat", reason: "Respiratory failure assessment" },
    ],
    imaging: [
      { type: "X-Ray", region: "Chest PA", urgency: "urgent", reason: "Confirm pneumonia, lobar/segmental infiltrates" },
      { type: "CT", region: "Chest HRCT", urgency: "routine", reason: "If CXR inconclusive or complicated" },
    ],
    referrals: [{ specialty: "Pulmonology", urgency: "urgent", reason: "Severe CAP or no response to treatment" }],
    notes: "CURB-65 score to assess severity. Hospitalize if CURB-65 ≥ 2.",
  },
  {
    id: "asthma", name: "Bronchial Asthma", icd10: "J45.9",
    system: "Respiratory", severity: "moderate", prevalence: "common",
    symptoms: ["wheezing", "breathlessness", "cough", "chest tightness", "nocturnal cough", "exercise intolerance"],
    redFlags: ["silent chest", "SpO2 < 92%", "unable to speak in sentences", "cyanosis"],
    medications: [
      { drug: "Salbutamol MDI 100mcg", dose: "2 puffs", route: "Inhaled", frequency: "PRN (rescue)", duration: "As needed", notes: "SABA — first reliever" },
      { drug: "Salbutamol Nebulisation 2.5mg", dose: "2.5mg in 3ml NS", route: "Inhaled", frequency: "Q20 min x3 then Q4h", duration: "Acute attack", notes: "Emergency bronchospasm" },
      { drug: "Formoterol + Budesonide MDI (Symbicort)", dose: "1–2 puffs", route: "Inhaled", frequency: "BD", duration: "Long-term", notes: "ICS+LABA — Step 3+ maintenance" },
      { drug: "Budesonide 200mcg MDI", dose: "1–2 puffs", route: "Inhaled", frequency: "BD", duration: "Long-term", notes: "ICS monotherapy — Step 2" },
      { drug: "Fluticasone/Salmeterol 250/25mcg", dose: "2 puffs", route: "Inhaled", frequency: "BD", duration: "Long-term", notes: "Alternative ICS+LABA" },
      { drug: "Tiotropium 18mcg", dose: "1 cap inhaled", route: "Inhaled", frequency: "OD", duration: "Long-term", notes: "LAMA add-on — Step 4 uncontrolled asthma" },
      { drug: "Montelukast 10mg", dose: "10mg", route: "Oral", frequency: "OD (night)", duration: "Long-term", notes: "LTRA — adjunct for allergic asthma" },
      { drug: "Prednisolone 30–40mg", dose: "30–40mg", route: "Oral", frequency: "OD morning", duration: "5–7 days", notes: "Oral steroid burst — acute attack" },
      { drug: "IV Hydrocortisone 200mg", dose: "200mg", route: "IV", frequency: "Q6h", duration: "Until oral tolerated", notes: "⚠️ Severe acute asthma — IV steroid" },
      { drug: "Ipratropium Bromide 500mcg Nebulisation", dose: "500mcg", route: "Inhaled", frequency: "Q4–6h", duration: "Acute attack", notes: "SAMA — add-on in A&E" },
      { drug: "IV Magnesium Sulphate 2g", dose: "2g in 100ml NS", route: "IV", frequency: "Stat over 20 min", duration: "Once", notes: "⚠️ Life-threatening asthma — last resort bronchodilator" },
      { drug: "Omalizumab 300mg SC", dose: "300mg", route: "IM", frequency: "Monthly", duration: "Long-term", notes: "Severe allergic asthma — high IgE" },
    ],
    labTests: [
      { name: "CBC with Eosinophil count", code: "CBC-EOS", urgency: "routine", reason: "Eosinophilia in allergic asthma" },
      { name: "IgE (Total)", code: "IgE", urgency: "routine", reason: "Allergic component" },
      { name: "ABG", code: "ABG", urgency: "stat", reason: "Acute severe asthma" },
      { name: "Allergy Panel (RAST)", code: "RAST", urgency: "routine", reason: "Identify triggers" },
    ],
    imaging: [
      { type: "X-Ray", region: "Chest PA", urgency: "routine", reason: "Exclude pneumothorax, infection" },
      { type: "PFT", region: "Spirometry", urgency: "routine", reason: "Confirm diagnosis, FEV1/FVC ratio" },
    ],
    referrals: [{ specialty: "Pulmonology", urgency: "routine", reason: "Uncontrolled asthma, step-up therapy" }],
    notes: "Check inhaler technique. Step-up GINA guidelines for uncontrolled asthma.",
  },
  {
    id: "copd", name: "COPD Exacerbation", icd10: "J44.1",
    system: "Respiratory", severity: "severe", prevalence: "common",
    symptoms: ["breathlessness", "chronic cough", "sputum", "wheezing", "fatigue", "smoking history"],
    redFlags: ["SpO2 < 88%", "confusion", "cyanosis", "use of accessory muscles"],
    medications: [
      { drug: "Salbutamol + Ipratropium (Duolin) Neb", dose: "2.5ml", route: "Inhaled", frequency: "Q20 min x3, then Q4–6h", duration: "Acute phase", notes: "SABA + SAMA — first-line bronchodilator" },
      { drug: "Tiotropium 18mcg DPI", dose: "1 cap", route: "Inhaled", frequency: "OD", duration: "Long-term", notes: "LAMA — maintenance therapy" },
      { drug: "Formoterol + Budesonide MDI", dose: "2 puffs", route: "Inhaled", frequency: "BD", duration: "Long-term", notes: "ICS+LABA maintenance" },
      { drug: "Prednisolone 40mg", dose: "40mg", route: "Oral", frequency: "OD", duration: "5 days", notes: "Systemic steroid burst — speeds recovery" },
      { drug: "IV Hydrocortisone 100mg", dose: "100mg", route: "IV", frequency: "Q6h", duration: "Until oral tolerated", notes: "Severe exacerbation — IV steroid" },
      { drug: "Amoxicillin-Clavulanate 625mg", dose: "625mg", route: "Oral", frequency: "TDS", duration: "5–7 days", notes: "Antibiotic — if purulent sputum" },
      { drug: "Doxycycline 100mg", dose: "100mg", route: "Oral", frequency: "BD", duration: "5–7 days", notes: "Alternative antibiotic" },
      { drug: "Levofloxacin 500mg", dose: "500mg", route: "Oral", frequency: "OD", duration: "7 days", notes: "If Pseudomonas risk" },
      { drug: "Theophylline 200mg SR", dose: "200mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Add-on bronchodilator — monitor levels" },
      { drug: "Roflumilast 500mcg", dose: "500mcg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "PDE-4 inhibitor — reduces exacerbations (GOLD D)" },
      { drug: "Oxygen Therapy", dose: "24–28% via Venturi mask", route: "Inhaled", frequency: "Continuous", duration: "Acute phase", notes: "⚠️ Target SpO2 88–92% only — avoid hyperoxygenation" },
    ],
    labTests: [
      { name: "ABG", code: "ABG", urgency: "stat", reason: "Type II respiratory failure" },
      { name: "CBC", code: "CBC", urgency: "urgent", reason: "Polycythaemia, infection" },
      { name: "Sputum C&S", code: "SPUTUM-CS", urgency: "urgent", reason: "Bacterial trigger" },
    ],
    imaging: [
      { type: "X-Ray", region: "Chest PA", urgency: "urgent", reason: "Hyperinflation, pneumothorax, consolidation" },
      { type: "CT", region: "Chest HRCT", urgency: "routine", reason: "Emphysema extent, bullae" },
      { type: "PFT", region: "Full PFT", urgency: "routine", reason: "Post-exacerbation — obstructive pattern" },
      { type: "ECG", region: "12-lead", urgency: "urgent", reason: "Cor pulmonale, arrhythmia" },
    ],
    referrals: [{ specialty: "Pulmonology", urgency: "urgent", reason: "Severe exacerbation, NIV requirement" }],
    notes: "Controlled O2 therapy — target SpO2 88-92%. Avoid high-flow O2.",
  },
  // ── CARDIAC ──────────────────────────────────────────────────────────────────
  {
    id: "acs", name: "Acute Coronary Syndrome (ACS)", icd10: "I24.9",
    system: "Cardiac", severity: "emergency", prevalence: "common",
    symptoms: ["chest pain", "left arm pain", "jaw pain", "sweating", "nausea", "breathlessness", "palpitations"],
    redFlags: ["crushing chest pain", "radiation to arm/jaw", "ST elevation", "hypotension", "syncope"],
    medications: [
      { drug: "Aspirin 325mg (STAT chew)", dose: "325mg", route: "Oral", frequency: "Stat", duration: "Once → then 75mg OD", notes: "⚠️ LOAD IMMEDIATELY — dual antiplatelet" },
      { drug: "Clopidogrel 300mg (STAT)", dose: "300mg", route: "Oral", frequency: "Stat", duration: "Once → then 75mg OD", notes: "Dual antiplatelet with Aspirin x12 months" },
      { drug: "Ticagrelor 180mg (STAT)", dose: "180mg", route: "Oral", frequency: "Stat", duration: "Once → then 90mg BD", notes: "Alternative to Clopidogrel — preferred in STEMI" },
      { drug: "Nitroglycerine 0.5mg SL", dose: "0.5mg", route: "Sublingual", frequency: "Q5 min x3 PRN", duration: "Acute pain", notes: "Vasodilator — avoid if BP <90 or right MI" },
      { drug: "IV Morphine 2–4mg", dose: "2–4mg", route: "IV", frequency: "Q5–10 min PRN", duration: "Until pain-free", notes: "Analgesic — titrate to pain score" },
      { drug: "Atorvastatin 80mg", dose: "80mg", route: "Oral", frequency: "OD night", duration: "Long-term", notes: "High-intensity statin — plaque stabilisation" },
      { drug: "Metoprolol 25mg", dose: "25mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Beta-blocker — reduce HR, mortality benefit in MI" },
      { drug: "Ramipril 2.5mg", dose: "2.5mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "ACEi — start post-MI if stable, esp. with EF <40%" },
      { drug: "LMWH (Enoxaparin) 1mg/kg", dose: "1mg/kg", route: "IM", frequency: "BD", duration: "5–7 days", notes: "Anticoagulation — NSTEMI/UA" },
      { drug: "IV Unfractionated Heparin", dose: "60 IU/kg bolus → 12 IU/kg/h", route: "IV", frequency: "Continuous", duration: "Until PCI", notes: "STEMI pre-cath anticoagulation" },
      { drug: "Fondaparinux 2.5mg", dose: "2.5mg", route: "IM", frequency: "OD", duration: "Up to 8 days", notes: "Alternative anticoagulant — lower bleeding risk" },
      { drug: "Oxygen 2–4L/min", dose: "2–4 LPM", route: "Inhaled", frequency: "Continuous", duration: "Until SpO2 >95%", notes: "Only if SpO2 <90% — avoid routine O2" },
    ],
    labTests: [
      { name: "Troponin I / T (serial)", code: "TROP", urgency: "stat", reason: "Myocardial injury marker" },
      { name: "CK-MB", code: "CKMB", urgency: "stat", reason: "Myocardial necrosis" },
      { name: "CBC, BMP, Electrolytes", code: "BASIC-PANEL", urgency: "stat", reason: "Baseline metabolic assessment" },
      { name: "Lipid Profile", code: "LIPID", urgency: "urgent", reason: "Cardiovascular risk" },
      { name: "INR / PT / aPTT", code: "COAG", urgency: "urgent", reason: "Pre-anticoagulation baseline" },
      { name: "BNP / NT-proBNP", code: "BNP", urgency: "urgent", reason: "Heart failure component" },
    ],
    imaging: [
      { type: "ECG", region: "12-lead STAT", urgency: "stat", reason: "ST changes, LBBB, Q waves" },
      { type: "Echo", region: "2D Echo with Doppler", urgency: "urgent", reason: "Wall motion abnormality, EF" },
      { type: "X-Ray", region: "Chest PA", urgency: "urgent", reason: "Pulmonary edema, cardiomegaly" },
    ],
    referrals: [{ specialty: "Cardiology / Cath Lab", urgency: "emergency", reason: "Primary PCI within 90 minutes for STEMI" }],
    notes: "⚠️ EMERGENCY — call for STEMI activation if ST elevation. Do NOT delay reperfusion.",
  },
  {
    id: "hypertension", name: "Hypertension", icd10: "I10",
    system: "Cardiac", severity: "moderate", prevalence: "common",
    symptoms: ["headache", "dizziness", "palpitations", "blurred vision", "nosebleed"],
    redFlags: ["BP > 180/120", "chest pain", "confusion", "vision loss", "focal neuro deficit"],
    medications: [
      { drug: "Amlodipine 5mg", dose: "5–10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "1st line CCB — well tolerated" },
      { drug: "Telmisartan 40mg", dose: "40–80mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "ARB — preferred in DM + HTN; avoid in pregnancy" },
      { drug: "Losartan 50mg", dose: "50–100mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "ARB alternative — beneficial in CKD" },
      { drug: "Ramipril 5mg", dose: "5–10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "ACEi — preferred post-MI, DM, HF" },
      { drug: "Enalapril 5mg", dose: "5–20mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "ACEi alternative" },
      { drug: "Hydrochlorothiazide 12.5mg", dose: "12.5–25mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "Thiazide diuretic — add-on; monitor K+" },
      { drug: "Indapamide 1.5mg SR", dose: "1.5mg", route: "Oral", frequency: "OD morning", duration: "Long-term", notes: "Alternative thiazide-like — less metabolic effects" },
      { drug: "Metoprolol 25mg", dose: "25–50mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Beta-blocker — add-on; preferred if HR elevated or IHD" },
      { drug: "Spironolactone 25mg", dose: "25–50mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "4th line for resistant HTN; monitor creatinine" },
      { drug: "IV Labetalol 20mg", dose: "20mg", route: "IV", frequency: "Q10 min (max 300mg)", duration: "Hypertensive emergency", notes: "⚠️ Hypertensive urgency/emergency IV agent" },
      { drug: "Nifedipine 10mg SL", dose: "10mg", route: "Sublingual", frequency: "Stat", duration: "Hypertensive urgency", notes: "Rapid BP reduction — use cautiously" },
    ],
    labTests: [
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Baseline" },
      { name: "RFT (Creatinine, BUN, eGFR)", code: "RFT", urgency: "routine", reason: "Renal targets — end-organ damage" },
      { name: "Electrolytes (Na, K)", code: "ELEC", urgency: "routine", reason: "Pre-diuretic baseline, hypokalemia risk" },
      { name: "Lipid Profile", code: "LIPID", urgency: "routine", reason: "Cardiovascular risk stratification" },
      { name: "FBS / HbA1c", code: "DM-SCREEN", urgency: "routine", reason: "Co-morbid diabetes screening" },
      { name: "Urine Microalbumin / Protein-Creatinine ratio", code: "URINE-MICRO", urgency: "routine", reason: "Early renal damage" },
    ],
    imaging: [
      { type: "ECG", region: "12-lead", urgency: "routine", reason: "LVH, strain pattern" },
      { type: "Echo", region: "2D Echo", urgency: "routine", reason: "LVH, diastolic dysfunction" },
      { type: "USG", region: "Abdomen + Renal Doppler", urgency: "routine", reason: "Renal artery stenosis, renal size" },
    ],
    referrals: [{ specialty: "Cardiology", urgency: "urgent", reason: "Hypertensive urgency/emergency, resistant HTN" }],
    notes: "Target BP < 130/80mmHg. Lifestyle modification (low sodium, exercise, weight loss).",
  },
  {
    id: "heartfailure", name: "Heart Failure (Decompensated)", icd10: "I50.9",
    system: "Cardiac", severity: "severe", prevalence: "common",
    symptoms: ["breathlessness", "orthopnea", "leg swelling", "fatigue", "paroxysmal nocturnal dyspnea", "palpitations"],
    redFlags: ["SpO2 < 90%", "acute pulmonary edema", "cardiogenic shock"],
    medications: [
      { drug: "Furosemide 40mg", dose: "40–80mg", route: "Oral", frequency: "BD", duration: "Until euvolemic", notes: "Loop diuretic — adjust dose to diuresis (target 1–1.5L/day)" },
      { drug: "IV Furosemide 40mg", dose: "40–80mg", route: "IV", frequency: "BD–TDS", duration: "Acute decompensation", notes: "⚠️ Acute pulmonary oedema — IV push" },
      { drug: "Sacubitril/Valsartan 50mg (Entresto)", dose: "50–200mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "ARNi — superior to ACEi in HFrEF. Don't co-use with ACEi" },
      { drug: "Ramipril 5mg", dose: "5–10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "ACEi — if Sacubitril unavailable" },
      { drug: "Carvedilol 3.125mg", dose: "3.125–25mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Beta-blocker — start low when dry, titrate q2 weeks" },
      { drug: "Bisoprolol 1.25mg", dose: "1.25–10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "Alternative cardioselective BB" },
      { drug: "Spironolactone 25mg", dose: "25–50mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "MRA — EF <35%; monitor K+ and Cr" },
      { drug: "Empagliflozin 10mg", dose: "10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "SGLT2i — HFrEF + HFpEF; cardio-renal protection" },
      { drug: "Digoxin 0.125mg", dose: "0.125–0.25mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "Rate control in AF with HF; monitor levels" },
      { drug: "IV GTN (Nitroglycerine) infusion", dose: "5–10 mcg/min", route: "IV", frequency: "Continuous", duration: "Acute pulmonary oedema", notes: "⚠️ Vasodilator — reduce preload; avoid if SBP <90" },
      { drug: "IV Dopamine 5–10 mcg/kg/min", dose: "5–10 mcg/kg/min", route: "IV", frequency: "Continuous", duration: "Cardiogenic shock", notes: "⚠️ Inotrope — cardiogenic shock" },
    ],
    labTests: [
      { name: "BNP / NT-proBNP", code: "BNP", urgency: "urgent", reason: "HF severity and prognosis" },
      { name: "CBC, RFT, Electrolytes", code: "BASIC", urgency: "urgent", reason: "Baseline and diuretic monitoring" },
      { name: "LFT", code: "LFT", urgency: "urgent", reason: "Congestive hepatopathy" },
      { name: "Thyroid Function (TSH)", code: "TSH", urgency: "routine", reason: "Thyroid-induced HF" },
    ],
    imaging: [
      { type: "ECG", region: "12-lead", urgency: "urgent", reason: "Arrhythmia, ischemia, LVH" },
      { type: "Echo", region: "2D Doppler Echo", urgency: "urgent", reason: "EF, wall motion, valvular disease" },
      { type: "X-Ray", region: "Chest PA", urgency: "urgent", reason: "Pulmonary edema, cardiomegaly" },
    ],
    referrals: [{ specialty: "Cardiology", urgency: "urgent", reason: "All decompensated HF patients" }],
    notes: "Classify HFrEF vs HFpEF. Fluid restrict 1.5L/day. Daily weight monitoring.",
  },
  // ── GI ───────────────────────────────────────────────────────────────────────
  {
    id: "gerd", name: "GERD / Acid Peptic Disease", icd10: "K21.0",
    system: "Gastrointestinal", severity: "mild", prevalence: "common",
    symptoms: ["heartburn", "regurgitation", "chest pain", "bloating", "nausea", "sour taste", "epigastric pain"],
    redFlags: ["dysphagia", "weight loss", "hematemesis", "anemia"],
    medications: [
      { drug: "Pantoprazole 40mg", dose: "40mg", route: "Oral", frequency: "OD (30 min before breakfast)", duration: "4–8 weeks", notes: "1st line PPI — most common" },
      { drug: "Omeprazole 20mg", dose: "20–40mg", route: "Oral", frequency: "OD before breakfast", duration: "4–8 weeks", notes: "PPI alternative" },
      { drug: "Rabeprazole 20mg", dose: "20mg", route: "Oral", frequency: "OD", duration: "4–8 weeks", notes: "PPI — fewer drug interactions" },
      { drug: "Esomeprazole 40mg", dose: "40mg", route: "Oral", frequency: "OD", duration: "4–8 weeks", notes: "S-isomer PPI — erosive GERD" },
      { drug: "Domperidone 10mg", dose: "10mg", route: "Oral", frequency: "TDS before meals", duration: "4 weeks", notes: "Prokinetic — bloating, regurgitation" },
      { drug: "Metoclopramide 10mg", dose: "10mg", route: "Oral", frequency: "TDS before meals", duration: "2 weeks", notes: "Prokinetic alternative — short course only" },
      { drug: "Antacid (Gelusil / Gaviscon)", dose: "10–15ml", route: "Oral", frequency: "PRN after meals and at bedtime", duration: "PRN", notes: "Symptomatic relief" },
      { drug: "Sucralfate 1g", dose: "1g", route: "Oral", frequency: "QDS before meals", duration: "4–8 weeks", notes: "Mucosal protectant — peptic ulcer" },
      { drug: "H. Pylori Eradication: Amoxicillin 1g + Clarithromycin 500mg + Pantoprazole 40mg", dose: "Standard triple", route: "Oral", frequency: "BD", duration: "14 days", notes: "If H. pylori positive" },
    ],
    labTests: [
      { name: "H. pylori Antigen (Stool)", code: "Hpylori-stool", urgency: "routine", reason: "Eradication if positive" },
      { name: "H. pylori Serology (ELISA)", code: "Hpylori-IgG", urgency: "routine", reason: "Alternative test" },
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Occult bleeding — anemia" },
    ],
    imaging: [
      { type: "Endoscopy", region: "Upper GI Endoscopy", urgency: "routine", reason: "Persistent/alarm symptoms — mucosal assessment" },
      { type: "USG", region: "Abdomen", urgency: "routine", reason: "Exclude hepatobiliary pathology" },
    ],
    referrals: [{ specialty: "Gastroenterology", urgency: "routine", reason: "Refractory GERD, Barrett's esophagus" }],
    notes: "Head-of-bed elevation, avoid late meals, avoid NSAIDs, coffee, alcohol.",
  },
  {
    id: "ibs", name: "Irritable Bowel Syndrome", icd10: "K58.9",
    system: "Gastrointestinal", severity: "mild", prevalence: "common",
    symptoms: ["abdominal pain", "bloating", "diarrhea", "constipation", "mucous in stool", "incomplete evacuation"],
    redFlags: ["blood in stool", "weight loss", "nocturnal diarrhea", "age > 50 onset", "family history CRC"],
    medications: [
      { drug: "Mebeverine 135mg", dose: "135mg", route: "Oral", frequency: "TDS before meals", duration: "4-8 weeks" },
      { drug: "Ispaghula Husk (Psyllium)", dose: "5g", route: "Oral", frequency: "BD with water", duration: "Long-term" },
      { drug: "Loperamide 2mg", dose: "2mg", route: "Oral", frequency: "PRN after loose stool", duration: "PRN", notes: "IBS-D only" },
    ],
    labTests: [
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Anemia, eosinophilia" },
      { name: "ESR / CRP", code: "INFLAM", urgency: "routine", reason: "Exclude IBD" },
      { name: "Stool Routine + Culture", code: "STOOL-RC", urgency: "routine", reason: "Infection, parasite" },
      { name: "Celiac Antibody (Anti-tTG IgA)", code: "CELIAC", urgency: "routine", reason: "Celiac disease mimics IBS" },
      { name: "Thyroid Function (TSH)", code: "TSH", urgency: "routine", reason: "Thyroid-related bowel changes" },
      { name: "Stool Calprotectin", code: "CALP", urgency: "routine", reason: "IBD marker — elevated indicates organicity" },
    ],
    imaging: [
      { type: "USG", region: "Abdomen + Pelvis", urgency: "routine", reason: "Structural pathology" },
      { type: "Endoscopy", region: "Colonoscopy", urgency: "routine", reason: "Alarm features — exclude IBD, CRC" },
    ],
    referrals: [{ specialty: "Gastroenterology", urgency: "routine", reason: "Alarm features, refractory symptoms" }],
    notes: "Rome IV criteria. Low-FODMAP diet counselling. Address anxiety/stress.",
  },
  {
    id: "appendicitis", name: "Acute Appendicitis", icd10: "K37",
    system: "Gastrointestinal", severity: "severe", prevalence: "common",
    symptoms: ["abdominal pain", "right iliac fossa pain", "nausea", "vomiting", "fever", "anorexia", "rebound tenderness"],
    redFlags: ["peritonitis", "rigid abdomen", "high fever", "perforation signs"],
    medications: [
      { drug: "IV Ceftriaxone 1g", dose: "1g", route: "IV", frequency: "BD", duration: "Pre-op prophylaxis" },
      { drug: "IV Metronidazole 500mg", dose: "500mg", route: "IV", frequency: "TDS", duration: "Pre-op + post-op" },
      { drug: "IV Paracetamol 1g", dose: "1g", route: "IV", frequency: "TDS PRN", duration: "Pre-op analgesia" },
    ],
    labTests: [
      { name: "CBC with Differential", code: "CBC-DIFF", urgency: "stat", reason: "Leukocytosis — neutrophilia" },
      { name: "CRP", code: "CRP", urgency: "stat", reason: "Elevated in appendicitis" },
      { name: "Urine Routine", code: "URINE-R", urgency: "stat", reason: "Exclude renal colic / UTI" },
      { name: "Urine / Serum Beta-hCG", code: "BHCG", urgency: "stat", reason: "Exclude ectopic pregnancy (females)" },
    ],
    imaging: [
      { type: "USG", region: "Abdomen + RIF", urgency: "urgent", reason: "Visualize appendix — first-line" },
      { type: "CT", region: "Abdomen + Pelvis (contrast)", urgency: "urgent", reason: "Gold standard — if USG inconclusive" },
      { type: "X-Ray", region: "Abdomen Erect", urgency: "urgent", reason: "Perforation — free air under diaphragm" },
    ],
    referrals: [{ specialty: "General Surgery", urgency: "emergency", reason: "Surgical consultation — appendicectomy" }],
    notes: "Alvarado score ≥ 7 — surgical. Keep NBM. IV fluids.",
  },
  // ── NEUROLOGICAL ─────────────────────────────────────────────────────────────
  {
    id: "migraine", name: "Migraine", icd10: "G43.9",
    system: "Neurological", severity: "moderate", prevalence: "common",
    symptoms: ["headache", "nausea", "vomiting", "photophobia", "phonophobia", "aura", "throbbing headache", "unilateral headache"],
    redFlags: ["thunderclap headache", "fever + neck stiffness", "focal deficit", "papilledema", "first severe headache"],
    medications: [
      { drug: "Sumatriptan 50mg", dose: "50–100mg", route: "Oral", frequency: "Stat at onset", duration: "PRN", notes: "Triptan — gold standard abortive; avoid in CVD/HTN" },
      { drug: "Zolmitriptan 2.5mg", dose: "2.5–5mg", route: "Oral", frequency: "Stat at onset", duration: "PRN", notes: "Alternative triptan" },
      { drug: "Naproxen 500mg", dose: "500mg", route: "Oral", frequency: "BD", duration: "2–3 days", notes: "NSAID — mild-moderate migraine" },
      { drug: "Aspirin 900mg + Metoclopramide 10mg", dose: "As above", route: "Oral", frequency: "Stat", duration: "PRN", notes: "First-line abortive if no triptan" },
      { drug: "Metoclopramide 10mg", dose: "10mg", route: "Oral", frequency: "TDS PRN", duration: "For nausea", notes: "Antiemetic + prokinetic" },
      { drug: "Domperidone 10mg", dose: "10mg", route: "Oral", frequency: "TDS", duration: "Attack duration", notes: "Antiemetic alternative" },
      { drug: "Propranolol 40mg", dose: "40–80mg", route: "Oral", frequency: "BD", duration: "Long-term (prophylaxis)", notes: "Beta-blocker prophylaxis — if ≥4 attacks/month" },
      { drug: "Topiramate 25mg", dose: "25–100mg", route: "Oral", frequency: "BD", duration: "Long-term (prophylaxis)", notes: "Titrate up slowly. Teratogenic — contraception needed" },
      { drug: "Amitriptyline 10mg", dose: "10–75mg", route: "Oral", frequency: "OD night", duration: "Long-term (prophylaxis)", notes: "TCA prophylaxis — also for tension-type overlap" },
      { drug: "Valproate 500mg", dose: "500–1000mg", route: "Oral", frequency: "BD", duration: "Long-term (prophylaxis)", notes: "Effective prophylaxis. ⚠️ Avoid in women of childbearing age" },
      { drug: "Flunarizine 10mg", dose: "10mg", route: "Oral", frequency: "OD night", duration: "Long-term (prophylaxis)", notes: "Calcium channel blocker prophylaxis — common in India" },
      { drug: "IV Ketorolac 30mg", dose: "30mg", route: "IV", frequency: "Stat", duration: "Once", notes: "ED setting — abortive IV NSAID" },
    ],
    labTests: [],
    imaging: [
      { type: "MRI", region: "Brain with MRA", urgency: "routine", reason: "First migraine, atypical, progressive — exclude structural cause" },
      { type: "CT", region: "Brain (non-contrast)", urgency: "urgent", reason: "Thunderclap headache — SAH" },
    ],
    referrals: [{ specialty: "Neurology", urgency: "routine", reason: "Frequent attacks, prophylaxis failure, atypical features" }],
    notes: "Headache diary. Identify triggers (stress, hormones, food). Limit analgesic to < 10 days/month.",
  },
  {
    id: "stroke", name: "Acute Ischaemic Stroke / TIA", icd10: "I63.9",
    system: "Neurological", severity: "emergency", prevalence: "common",
    symptoms: ["facial droop", "arm weakness", "speech difficulty", "sudden headache", "vision loss", "dizziness", "confusion"],
    redFlags: ["FAST positive", "onset < 4.5 hours", "seizures", "coma"],
    medications: [
      { drug: "Aspirin 300mg STAT", dose: "300mg", route: "Oral", frequency: "Stat", duration: "Then 75–150mg OD long-term", notes: "Antiplatelet — give in A&E immediately" },
      { drug: "Clopidogrel 75mg", dose: "75mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "If aspirin intolerant, or dual antiplatelet in TIA" },
      { drug: "Atorvastatin 80mg", dose: "80mg", route: "Oral", frequency: "OD night", duration: "Long-term", notes: "High-intensity statin — plaque stabilisation" },
      { drug: "tPA (Alteplase) 0.9mg/kg IV", dose: "0.9mg/kg", route: "IV", frequency: "Stat (max 90mg)", duration: "Once over 60 min", notes: "⚠️ Thrombolysis — only if within 4.5h window; check contraindications" },
      { drug: "IV Tenecteplase 0.25mg/kg", dose: "0.25mg/kg", route: "IV", frequency: "Stat single bolus", duration: "Once", notes: "Alternative thrombolytic — easier to administer" },
      { drug: "Warfarin (target INR 2–3)", dose: "Individualised", route: "Oral", frequency: "OD", duration: "Long-term", notes: "Anticoagulation — AF-related cardioembolic stroke" },
      { drug: "Rivaroxaban 20mg", dose: "20mg", route: "Oral", frequency: "OD with dinner", duration: "Long-term", notes: "DOAC — preferred over Warfarin in AF" },
      { drug: "Apixaban 5mg", dose: "5mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "DOAC alternative" },
      { drug: "Labetalol or Nicardipine IV", dose: "20mg IV", route: "IV", frequency: "Q10 min", duration: "Hypertensive emergency", notes: "⚠️ Only treat BP if >220/120 in ischaemic stroke" },
    ],
    labTests: [
      { name: "CBC, PT/INR, aPTT", code: "COAG-PANEL", urgency: "stat", reason: "Anticoagulation eligibility" },
      { name: "Random Blood Glucose", code: "RBG", urgency: "stat", reason: "Hypoglycemia mimicking stroke" },
      { name: "Electrolytes + Renal Function", code: "RFT-ELEC", urgency: "stat", reason: "Metabolic screening" },
      { name: "Lipid Profile, HbA1c", code: "RISK", urgency: "urgent", reason: "Risk factors" },
    ],
    imaging: [
      { type: "CT", region: "Brain Non-contrast STAT", urgency: "stat", reason: "Exclude hemorrhage before thrombolysis" },
      { type: "MRI", region: "Brain DWI + MRA", urgency: "urgent", reason: "Ischemic territory, vessel occlusion" },
      { type: "Echo", region: "2D Echo + TEE", urgency: "urgent", reason: "Cardioembolic source — LV thrombus, AF" },
      { type: "ECG", region: "12-lead", urgency: "stat", reason: "Atrial fibrillation — embolic source" },
    ],
    referrals: [{ specialty: "Neurology / Stroke Unit", urgency: "emergency", reason: "⚠️ Activate stroke code immediately" }],
    notes: "⚠️ TIME IS BRAIN — activate stroke protocol. Target CT within 25 min of arrival.",
  },
  // ── ENDOCRINE ─────────────────────────────────────────────────────────────────
  {
    id: "t2dm", name: "Type 2 Diabetes Mellitus", icd10: "E11",
    system: "Endocrine", severity: "moderate", prevalence: "common",
    symptoms: ["polyuria", "polydipsia", "polyphagia", "weight loss", "fatigue", "blurred vision", "recurrent infections", "slow wound healing"],
    redFlags: ["ketoacidosis", "HHS", "FBS > 500mg/dL", "altered consciousness"],
    medications: [
      { drug: "Metformin 500mg", dose: "500–1000mg", route: "Oral", frequency: "BD with meals", duration: "Long-term", notes: "1st line — titrate to 2g/day; check eGFR" },
      { drug: "Vildagliptin 50mg", dose: "50mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "DPP-4i — add-on, safe in CKD" },
      { drug: "Sitagliptin 100mg", dose: "50–100mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "DPP-4i alternative" },
      { drug: "Empagliflozin 10mg", dose: "10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "SGLT2i — cardio-renal benefit; avoid if eGFR <45" },
      { drug: "Dapagliflozin 10mg", dose: "10mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "SGLT2i alternative" },
      { drug: "Semaglutide 0.25mg SC", dose: "0.25–1mg", route: "IM", frequency: "Weekly SC", duration: "Long-term", notes: "GLP-1 RA — weight loss + CV benefit; titrate monthly" },
      { drug: "Liraglutide 0.6mg SC", dose: "0.6–1.8mg", route: "IM", frequency: "OD SC", duration: "Long-term", notes: "GLP-1 RA alternative" },
      { drug: "Glimepiride 2mg", dose: "2–4mg", route: "Oral", frequency: "OD before breakfast", duration: "Long-term", notes: "Sulfonylurea — low cost; hypoglycemia risk" },
      { drug: "Glipizide 5mg", dose: "5–20mg", route: "Oral", frequency: "OD BD", duration: "Long-term", notes: "Sulfonylurea alternative" },
      { drug: "Pioglitazone 15mg", dose: "15–30mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "TZD — insulin sensitiser; avoid in HF/NAFLD" },
      { drug: "Basal Insulin (Glargine/Detemir) 10U SC", dose: "10–20U", route: "IM", frequency: "OD (bedtime)", duration: "Long-term", notes: "Basal insulin — titrate 2U every 3 days to FBS target" },
      { drug: "Human Insulin 70/30 — 10U", dose: "10U", route: "IM", frequency: "BD before meals", duration: "If oral fails", notes: "Premix insulin — titrate to FBS <130" },
    ],
    labTests: [
      { name: "FBS / PPBS", code: "FBS-PPBS", urgency: "routine", reason: "Glycemic control" },
      { name: "HbA1c", code: "HBA1C", urgency: "routine", reason: "3-month glycemic average — target < 7%" },
      { name: "RFT (Creatinine, eGFR)", code: "RFT", urgency: "routine", reason: "Diabetic nephropathy" },
      { name: "Urine Microalbumin", code: "URINE-MICRO", urgency: "routine", reason: "Early nephropathy" },
      { name: "Lipid Profile", code: "LIPID", urgency: "routine", reason: "Cardiovascular risk" },
      { name: "LFT", code: "LFT", urgency: "routine", reason: "NAFLD, Metformin safety" },
      { name: "TSH", code: "TSH", urgency: "routine", reason: "Autoimmune association" },
    ],
    imaging: [
      { type: "ECG", region: "12-lead", urgency: "routine", reason: "Baseline — silent MI in DM" },
      { type: "USG", region: "Abdomen", urgency: "routine", reason: "NAFLD, fatty liver" },
    ],
    referrals: [
      { specialty: "Endocrinology", urgency: "routine", reason: "Complex diabetes, DKA, insulin titration" },
      { specialty: "Ophthalmology", urgency: "routine", reason: "Annual diabetic retinopathy screening" },
      { specialty: "Nephrology", urgency: "routine", reason: "eGFR < 45, proteinuria" },
    ],
    notes: "Target HbA1c < 7%. Annual foot exam, retinal exam, microalbumin screening.",
  },
  {
    id: "hypothyroid", name: "Hypothyroidism", icd10: "E03.9",
    system: "Endocrine", severity: "mild", prevalence: "common",
    symptoms: ["fatigue", "weight gain", "cold intolerance", "constipation", "dry skin", "hair loss", "depression", "bradycardia", "menstrual irregularity"],
    redFlags: ["myxedema coma", "bradycardia < 40", "hypothermia"],
    medications: [
      { drug: "Levothyroxine 50mcg", dose: "50mcg", route: "Oral", frequency: "OD (empty stomach)", duration: "Long-term", notes: "Start low, titrate 6-weekly" },
    ],
    labTests: [
      { name: "TSH", code: "TSH", urgency: "routine", reason: "Confirm diagnosis — TSH elevated" },
      { name: "Free T4 (FT4)", code: "FT4", urgency: "routine", reason: "Low FT4 in overt hypothyroidism" },
      { name: "Anti-TPO Antibody", code: "ANTI-TPO", urgency: "routine", reason: "Hashimoto's thyroiditis" },
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Macrocytic anemia" },
      { name: "Lipid Profile", code: "LIPID", urgency: "routine", reason: "Hyperlipidemia association" },
    ],
    imaging: [
      { type: "USG", region: "Thyroid", urgency: "routine", reason: "Goiter, nodule assessment" },
    ],
    referrals: [{ specialty: "Endocrinology", urgency: "routine", reason: "Resistant hypothyroid, pregnancy, nodule" }],
    notes: "Recheck TSH 6 weeks after dose change. Target TSH 0.5–2.5 mIU/L.",
  },
  // ── INFECTIOUS ───────────────────────────────────────────────────────────────
  {
    id: "dengue", name: "Dengue Fever", icd10: "A90",
    system: "Infectious", severity: "severe", prevalence: "common",
    symptoms: ["high fever", "headache", "retro-orbital pain", "myalgia", "arthralgia", "rash", "nausea", "vomiting", "bleeding"],
    redFlags: ["platelet < 20,000", "bleeding", "shock", "abdominal pain", "persistent vomiting"],
    medications: [
      { drug: "Paracetamol 650mg", dose: "650mg", route: "Oral", frequency: "TDS", duration: "Until afebrile 48h", notes: "AVOID NSAIDs/Aspirin" },
      { drug: "IV Fluids (NS/RL)", dose: "500ml", route: "IV", frequency: "As per protocol", duration: "PRN if unable to drink" },
    ],
    labTests: [
      { name: "NS1 Antigen (Dengue)", code: "NS1", urgency: "urgent", reason: "Positive in first 5 days" },
      { name: "Dengue IgM / IgG", code: "DENGUE-SEROL", urgency: "urgent", reason: "After day 5" },
      { name: "CBC with Platelet (daily)", code: "CBC-PLT", urgency: "urgent", reason: "Monitor platelet trend" },
      { name: "LFT", code: "LFT", urgency: "urgent", reason: "Transaminitis in dengue" },
      { name: "PT / aPTT", code: "COAG", urgency: "urgent", reason: "Coagulopathy in severe dengue" },
    ],
    imaging: [
      { type: "USG", region: "Abdomen", urgency: "urgent", reason: "Ascites, pleural effusion, gallbladder wall edema" },
      { type: "X-Ray", region: "Chest PA + Lateral", urgency: "urgent", reason: "Pleural effusion" },
    ],
    referrals: [{ specialty: "Internal Medicine", urgency: "urgent", reason: "Dengue warning signs — hospitalize" }],
    notes: "Monitor hematocrit daily. Platelet transfusion if < 10,000 or active bleeding.",
  },
  {
    id: "malaria", name: "Malaria", icd10: "B54",
    system: "Infectious", severity: "severe", prevalence: "common",
    symptoms: ["cyclical fever", "chills", "rigors", "headache", "myalgia", "nausea", "vomiting", "sweating", "splenomegaly"],
    redFlags: ["cerebral malaria", "severe anemia", "AKI", "hyperparasitemia", "jaundice"],
    medications: [
      { drug: "Artemether-Lumefantrine (AL) 80/480mg co-formulation", dose: "4 tabs", route: "Oral", frequency: "BD x3 days", duration: "3 days", notes: "Falciparum malaria — take with food" },
      { drug: "Chloroquine 500mg", dose: "500mg", route: "Oral", frequency: "Day 1: 600mg + 300mg after 6h; Day 2-3: 300mg OD", duration: "3 days", notes: "Vivax malaria" },
      { drug: "Primaquine 15mg", dose: "15mg", route: "Oral", frequency: "OD", duration: "14 days", notes: "Vivax — radical cure. Check G6PD first" },
    ],
    labTests: [
      { name: "Peripheral Blood Smear (PBS)", code: "PBS", urgency: "stat", reason: "Species ID and parasitemia density" },
      { name: "Malaria RDT (Rapid Antigen)", code: "MAL-RDT", urgency: "stat", reason: "Quick screening" },
      { name: "CBC", code: "CBC", urgency: "urgent", reason: "Anemia, thrombocytopenia" },
      { name: "G6PD Level", code: "G6PD", urgency: "urgent", reason: "Before Primaquine — risk of hemolysis" },
      { name: "RFT + LFT", code: "RFT-LFT", urgency: "urgent", reason: "Organ involvement" },
      { name: "Blood Glucose", code: "BG", urgency: "stat", reason: "Hypoglycemia risk" },
    ],
    imaging: [{ type: "USG", region: "Abdomen", urgency: "routine", reason: "Hepatosplenomegaly" }],
    referrals: [{ specialty: "Internal Medicine", urgency: "urgent", reason: "Severe/complicated malaria" }],
    notes: "Notifiable disease. Admit for falciparum or complicated malaria.",
  },
  {
    id: "uti", name: "Urinary Tract Infection", icd10: "N39.0",
    system: "Urological", severity: "mild", prevalence: "common",
    symptoms: ["dysuria", "frequency", "urgency", "suprapubic pain", "cloudy urine", "haematuria", "foul smelling urine"],
    redFlags: ["fever > 38.5°C", "flank pain", "costovertebral angle tenderness", "rigors — pyelonephritis"],
    medications: [
      { drug: "Nitrofurantoin 100mg MR", dose: "100mg", route: "Oral", frequency: "BD", duration: "5–7 days", notes: "1st line uncomplicated lower UTI; avoid if eGFR <30" },
      { drug: "Co-trimoxazole (Trimethoprim/Sulfamethoxazole) 960mg", dose: "960mg", route: "Oral", frequency: "BD", duration: "3 days", notes: "Only if local sensitivity <20% resistance" },
      { drug: "Trimethoprim 200mg", dose: "200mg", route: "Oral", frequency: "BD", duration: "3–5 days", notes: "Alternative for uncomplicated UTI" },
      { drug: "Pivmecillinam 200mg", dose: "200mg", route: "Oral", frequency: "TDS", duration: "3–7 days", notes: "Effective against ESBL-producing E. coli" },
      { drug: "Cefuroxime 250mg", dose: "250mg", route: "Oral", frequency: "BD", duration: "7 days", notes: "Pregnancy UTI or complicated lower UTI" },
      { drug: "Ciprofloxacin 500mg", dose: "500mg", route: "Oral", frequency: "BD", duration: "7 days", notes: "Pyelonephritis 1st line; avoid first in uncomplicated" },
      { drug: "Levofloxacin 750mg", dose: "750mg", route: "Oral", frequency: "OD", duration: "5 days", notes: "Alternative for pyelonephritis" },
      { drug: "IV Ceftriaxone 1–2g", dose: "1–2g", route: "IV", frequency: "OD", duration: "7–14 days", notes: "Severe pyelonephritis / urosepsis" },
      { drug: "IV Piperacillin-Tazobactam 4.5g", dose: "4.5g", route: "IV", frequency: "Q8h", duration: "7–10 days", notes: "Hospital-acquired UTI / ESBL organisms" },
      { drug: "Fosfomycin 3g", dose: "3g sachet", route: "Oral", frequency: "Single dose", duration: "Once", notes: "Single dose for uncomplicated UTI — excellent compliance" },
      { drug: "Phenazopyridine 200mg", dose: "200mg", route: "Oral", frequency: "TDS", duration: "Max 2 days", notes: "Urinary analgesic — symptomatic relief only" },
    ],
    labTests: [
      { name: "Urine Routine & Microscopy", code: "URINE-RM", urgency: "urgent", reason: "Pyuria, hematuria, casts" },
      { name: "Urine Culture & Sensitivity", code: "URINE-CS", urgency: "urgent", reason: "Pathogen + antibiotic sensitivity" },
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Infection severity" },
      { name: "RFT", code: "RFT", urgency: "routine", reason: "Upper tract involvement" },
    ],
    imaging: [
      { type: "USG", region: "KUB (Kidney, Ureter, Bladder)", urgency: "routine", reason: "Structural abnormality, stones, hydronephrosis" },
      { type: "CT", region: "CT-KUB (non-contrast)", urgency: "urgent", reason: "Renal calculi, if clinically suspected" },
    ],
    referrals: [{ specialty: "Urology", urgency: "routine", reason: "Recurrent UTI, structural anomaly, male UTI" }],
    notes: "Encourage adequate hydration (>2L/day). Culture before antibiotics.",
  },
  // ── MUSCULOSKELETAL ──────────────────────────────────────────────────────────
  {
    id: "ra", name: "Rheumatoid Arthritis", icd10: "M05.9",
    system: "Musculoskeletal", severity: "moderate", prevalence: "common",
    symptoms: ["joint pain", "joint swelling", "morning stiffness", "symmetrical arthritis", "hand swelling", "fatigue", "rheumatoid nodules"],
    redFlags: ["rapid joint destruction", "extra-articular features", "cervical spine involvement"],
    medications: [
      { drug: "Methotrexate 7.5mg", dose: "7.5–25mg", route: "Oral", frequency: "Once weekly", duration: "Long-term", notes: "1st line csDMARD — give with folic acid 5mg/week" },
      { drug: "Folic Acid 5mg", dose: "5mg", route: "Oral", frequency: "Once/week (not MTX day)", duration: "Long-term", notes: "Mandatory with MTX — reduces side effects" },
      { drug: "Hydroxychloroquine 200mg", dose: "200–400mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Adjunct csDMARD — annual ophthalmology review" },
      { drug: "Sulfasalazine 500mg", dose: "500mg (titrate to 1g)", route: "Oral", frequency: "BD–TDS", duration: "Long-term", notes: "csDMARD triple therapy with MTX + HCQ" },
      { drug: "Leflunomide 10mg", dose: "10–20mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "Alternative csDMARD if MTX intolerant" },
      { drug: "Prednisolone 10mg", dose: "10mg", route: "Oral", frequency: "OD morning", duration: "Bridge (3 months)", notes: "Systemic steroid — use short bridge only; taper slowly" },
      { drug: "IM Methylprednisolone 80mg", dose: "80mg", route: "IM", frequency: "Monthly PRN", duration: "Acute flare", notes: "IM steroid for rapid flare control" },
      { drug: "Ibuprofen 400mg", dose: "400mg", route: "Oral", frequency: "TDS with food", duration: "PRN flares", notes: "NSAID with PPI cover" },
      { drug: "Adalimumab 40mg SC", dose: "40mg", route: "IM", frequency: "Every 2 weeks", duration: "Long-term", notes: "Biologic (anti-TNF) — if csDMARD failure at 3–6 months" },
      { drug: "Etanercept 50mg SC", dose: "50mg", route: "IM", frequency: "Weekly", duration: "Long-term", notes: "Anti-TNF biologic alternative" },
      { drug: "Baricitinib 4mg", dose: "4mg", route: "Oral", frequency: "OD", duration: "Long-term", notes: "JAK inhibitor — biologic failure/intolerance; check DVT risk" },
      { drug: "Tofacitinib 5mg", dose: "5mg", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Alternative JAK inhibitor" },
    ],
    labTests: [
      { name: "Rheumatoid Factor (RF)", code: "RF", urgency: "routine", reason: "RA seropositive vs seronegative" },
      { name: "Anti-CCP Antibody", code: "ANTI-CCP", urgency: "routine", reason: "More specific for RA" },
      { name: "ESR / CRP", code: "ESR-CRP", urgency: "routine", reason: "Disease activity" },
      { name: "CBC, RFT, LFT", code: "SAFETY-LABS", urgency: "routine", reason: "Methotrexate monitoring" },
      { name: "ANA Panel", code: "ANA", urgency: "routine", reason: "Overlap syndrome exclusion" },
    ],
    imaging: [
      { type: "X-Ray", region: "Hands and Feet (Bilateral)", urgency: "routine", reason: "Erosions, joint space narrowing" },
      { type: "MRI", region: "Wrist/Hand", urgency: "routine", reason: "Early synovitis, erosions before X-ray changes" },
      { type: "USG", region: "Joints (Affected)", urgency: "routine", reason: "Synovitis, effusion, Power Doppler" },
    ],
    referrals: [{ specialty: "Rheumatology", urgency: "routine", reason: "All new RA diagnoses for DMARD initiation" }],
    notes: "Early aggressive DMARD therapy. Monitor LFT, CBC monthly on MTX.",
  },
  // ── PSYCHIATRIC ──────────────────────────────────────────────────────────────
  {
    id: "depression", name: "Major Depressive Disorder", icd10: "F32.9",
    system: "Psychiatric", severity: "moderate", prevalence: "common",
    symptoms: ["low mood", "anhedonia", "fatigue", "sleep disturbance", "appetite change", "poor concentration", "worthlessness", "suicidal ideation"],
    redFlags: ["active suicidal ideation", "psychosis", "severe self-neglect"],
    medications: [
      { drug: "Sertraline 50mg", dose: "50–200mg", route: "Oral", frequency: "OD morning", duration: "6–12 months", notes: "1st line SSRI — titrate to 100–200mg over 4–6 weeks" },
      { drug: "Escitalopram 10mg", dose: "10–20mg", route: "Oral", frequency: "OD", duration: "6–12 months", notes: "SSRI — best tolerability; preferred in elderly" },
      { drug: "Fluoxetine 20mg", dose: "20–60mg", route: "Oral", frequency: "OD morning", duration: "6–12 months", notes: "SSRI — longest half-life; best if adherence is concern" },
      { drug: "Mirtazapine 15mg", dose: "15–45mg", route: "Oral", frequency: "OD night", duration: "6–12 months", notes: "NaSSA — insomnia + poor appetite; sedating at low doses" },
      { drug: "Duloxetine 30mg", dose: "30–60mg", route: "Oral", frequency: "OD", duration: "6–12 months", notes: "SNRI — somatic symptoms, neuropathic pain co-morbidity" },
      { drug: "Venlafaxine 37.5mg", dose: "37.5–225mg", route: "Oral", frequency: "OD–BD", duration: "6–12 months", notes: "SNRI alternative — titrate gradually; monitor BP" },
      { drug: "Bupropion 150mg", dose: "150–300mg", route: "Oral", frequency: "BD", duration: "6–12 months", notes: "NDRI — avoid if seizure risk; useful if sexual dysfunction" },
      { drug: "Amitriptyline 25mg", dose: "25–150mg", route: "Oral", frequency: "OD night", duration: "6–12 months", notes: "TCA — 2nd line; neuropathic pain co-morbidity. Anticholinergic SE" },
      { drug: "Clonazepam 0.5mg", dose: "0.5–1mg", route: "Oral", frequency: "OD–BD PRN", duration: "Max 4 weeks only", notes: "Adjunct for acute anxiety — avoid long-term (dependence risk)" },
      { drug: "Lithium 400mg", dose: "400–800mg (target level 0.6–0.8 mmol/L)", route: "Oral", frequency: "BD", duration: "Long-term", notes: "Mood stabiliser for bipolar depression; monitor levels + TFT/RFT" },
    ],
    labTests: [
      { name: "TSH", code: "TSH", urgency: "routine", reason: "Hypothyroidism mimics depression" },
      { name: "CBC", code: "CBC", urgency: "routine", reason: "Anemia as cause of fatigue" },
      { name: "Vitamin B12 + D3", code: "VIT-B12-D3", urgency: "routine", reason: "Deficiency correlation with depression" },
    ],
    imaging: [],
    referrals: [{ specialty: "Psychiatry", urgency: "urgent", reason: "Suicidal ideation, psychosis, refractory depression" }],
    notes: "PHQ-9 score. Psychotherapy (CBT) alongside medication. Avoid in bipolar without mood stabiliser.",
  },
  // ── HAEMATOLOGICAL ──────────────────────────────────────────────────────────
  {
    id: "anaemia", name: "Iron-Deficiency Anaemia", icd10: "D50.9",
    system: "Haematological", severity: "moderate", prevalence: "common",
    symptoms: ["fatigue", "pallor", "breathlessness on exertion", "palpitations", "dizziness", "cold intolerance", "koilonychia", "angular stomatitis"],
    redFlags: ["Hb < 7g/dL", "hemodynamic instability", "cardiac failure"],
    medications: [
      { drug: "Ferrous Sulphate 200mg", dose: "200mg", route: "Oral", frequency: "TDS between meals", duration: "3–6 months", notes: "1st line oral iron. Take with Vit C; avoid with tea/antacids" },
      { drug: "Ferrous Fumarate 200mg", dose: "200mg", route: "Oral", frequency: "BD–TDS", duration: "3–6 months", notes: "Alternative oral iron — fewer GI side effects" },
      { drug: "Iron Polymaltose Complex (Feronia)", dose: "100mg elemental iron", route: "Oral", frequency: "OD", duration: "3–6 months", notes: "Better tolerated — can take with food" },
      { drug: "Vitamin C 500mg", dose: "500mg", route: "Oral", frequency: "OD with iron tablet", duration: "Long-term", notes: "Enhances iron absorption by ~30%" },
      { drug: "IV Iron Sucrose 200mg", dose: "200mg in 100ml NS", route: "IV", frequency: "Weekly x5 doses", duration: "5 weeks", notes: "If oral not tolerated / malabsorption / pre-operative" },
      { drug: "IV Ferric Carboxymaltose (Monofer) 500mg", dose: "500–1000mg", route: "IV", frequency: "Single or split dose", duration: "Once", notes: "Rapid total dose IV iron correction" },
      { drug: "Folic Acid 5mg", dose: "5mg", route: "Oral", frequency: "OD", duration: "3–6 months", notes: "Mixed deficiency — megaloblastic component" },
      { drug: "Cyanocobalamin (Vit B12) 1000mcg IM", dose: "1000mcg", route: "IM", frequency: "Weekly x4 then monthly", duration: "Long-term if B12 deficient", notes: "B12 deficiency anaemia" },
      { drug: "PRBC Transfusion (1–2 units)", dose: "1–2 units", route: "IV", frequency: "Stat", duration: "PRN", notes: "⚠️ Hb <7 or haemodynamically unstable — transfuse" },
      { drug: "Erythropoietin (EPO) 4000 IU", dose: "4000 IU SC", route: "IM", frequency: "3x/week", duration: "8–12 weeks", notes: "CKD-anaemia only. Monitor Hb and BP" },
    ],
    labTests: [
      { name: "CBC with Peripheral Smear", code: "CBC-PS", urgency: "urgent", reason: "Microcytic hypochromic anemia" },
      { name: "Serum Iron, TIBC, Ferritin", code: "IRON-PANEL", urgency: "urgent", reason: "Confirm iron deficiency — low ferritin, high TIBC" },
      { name: "Peripheral Blood Film", code: "PBF", urgency: "routine", reason: "Morphology — target cells, anisocytosis" },
      { name: "Reticulocyte Count", code: "RETIC", urgency: "routine", reason: "Marrow response" },
      { name: "Vitamin B12 + Folate", code: "VIT-B12-FOLATE", urgency: "routine", reason: "Mixed deficiency" },
    ],
    imaging: [
      { type: "Endoscopy", region: "Upper GI Endoscopy", urgency: "routine", reason: "Source of bleeding — peptic ulcer, cancer" },
    ],
    referrals: [
      { specialty: "Haematology", urgency: "urgent", reason: "Hb < 7, suspected haemolysis or bone marrow disease" },
      { specialty: "Gastroenterology", urgency: "routine", reason: "GI source of occult bleeding" },
    ],
    notes: "Find and treat the underlying cause. Supplement for ≥ 3 months after Hb normalises.",
  },
  // ── DERMATOLOGICAL ──────────────────────────────────────────────────────────
  {
    id: "urticaria", name: "Urticaria / Allergic Reaction", icd10: "L50.9",
    system: "Dermatological", severity: "moderate", prevalence: "common",
    symptoms: ["rash", "hives", "itching", "swelling", "wheals", "flushing", "angioedema"],
    redFlags: ["throat swelling", "stridor", "hypotension", "anaphylaxis"],
    medications: [
      { drug: "Cetirizine 10mg", dose: "10mg", route: "Oral", frequency: "OD", duration: "2–4 weeks", notes: "1st line non-sedating antihistamine" },
      { drug: "Levocetirizine 5mg", dose: "5mg", route: "Oral", frequency: "OD night", duration: "2–6 weeks", notes: "Alternative 2nd gen antihistamine" },
      { drug: "Fexofenadine 180mg", dose: "180mg", route: "Oral", frequency: "OD", duration: "4–6 weeks", notes: "Non-sedating — safe for drivers" },
      { drug: "Loratadine 10mg", dose: "10mg", route: "Oral", frequency: "OD", duration: "4 weeks", notes: "Alternative 2nd gen antihistamine" },
      { drug: "Hydroxyzine 25mg", dose: "25–50mg", route: "Oral", frequency: "TDS", duration: "Acute episode", notes: "Sedating 1st gen AH — use at night" },
      { drug: "Chlorpheniramine 4mg", dose: "4mg", route: "Oral", frequency: "TDS–QDS", duration: "3–5 days", notes: "1st gen sedating AH — acute urticaria" },
      { drug: "Prednisolone 30–40mg", dose: "30–40mg", route: "Oral", frequency: "OD morning", duration: "5 days", notes: "Severe acute urticaria / angioedema" },
      { drug: "Adrenaline (Epinephrine) 0.5mg IM", dose: "0.5mg (1:1000)", route: "IM", frequency: "Stat — repeat in 5 min if no response", duration: "Anaphylaxis emergency", notes: "⚠️ ANAPHYLAXIS — thigh IM immediately" },
      { drug: "Chlorpheniramine 10mg IV", dose: "10mg", route: "IV", frequency: "Stat", duration: "Post-Adrenaline in anaphylaxis", notes: "⚠️ IV antihistamine for anaphylaxis" },
      { drug: "Hydrocortisone 200mg IV", dose: "200mg", route: "IV", frequency: "Stat", duration: "Anaphylaxis", notes: "⚠️ IV steroid — 3rd drug in anaphylaxis after Epi + AH" },
      { drug: "Omalizumab 300mg SC", dose: "300mg", route: "IM", frequency: "Monthly", duration: "12 months", notes: "Anti-IgE biologic — chronic refractory urticaria >6 months" },
      { drug: "Montelukast 10mg", dose: "10mg", route: "Oral", frequency: "OD night", duration: "4–8 weeks", notes: "LTRA adjunct — anti-inflammatory add-on" },
    ],
    labTests: [
      { name: "CBC with Eosinophil", code: "CBC-EOS", urgency: "routine", reason: "Eosinophilia — allergic/parasitic" },
      { name: "IgE Total", code: "IGE", urgency: "routine", reason: "Atopic status" },
      { name: "Allergy Panel (Skin Prick/RAST)", code: "ALLERGY", urgency: "routine", reason: "Identify specific allergens" },
      { name: "Thyroid Function", code: "THYROID", urgency: "routine", reason: "Autoimmune urticaria association" },
    ],
    imaging: [],
    referrals: [{ specialty: "Dermatology / Allergy & Immunology", urgency: "routine", reason: "Chronic urticaria > 6 weeks" }],
    notes: "Identify and remove trigger. Avoid NSAIDs. Omalizumab for refractory cases.",
  },
];

